# Generated by Django 4.2.7 on 2025-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(
                blank=True,
                choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')],
                max_length=10,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
