# Generated by Django 4.2.7 on 2025-08-10 06:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20250807_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Automatically determined sentiment of the review', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='When the sentiment analysis was last performed', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score of the sentiment prediction (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='sentiment_scores',
            field=models.JSONField(blank=True, help_text='Detailed probability scores for each sentiment category', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
